#端口
server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

#配置Rabbitmq的安装地址、端口以及账户信息
  rabbitmq:
    name: spirng-boot-rabbitmq
    rabbitmq: host=127.0.0.1
    port: 5672
    username: admin
    password: admin

#配置文件传输
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      #单个数据的大小
      max-file-size: 500MB
      #总数据的大小
      max-request-size: 1000MB

#redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
#spring-security
  #自定义用户名和密码
#  security:
#    user:
#      name: x
#      password: 1

#    lettuce:
#    pool:
#      #最大连接数
#      max-active: 8
#      #最大阻塞等待时间
#      max-wait: 6000
#      #最大空闲连接
#      max-idle: 8
#      #最小空闲连接
#      min-idle: 0
#      timeout: 5000
#    database: 0

# 去除启动时大量的Positive matches信息
logging.level.org.springframework.boot.autoconfigure: ERROR

#配置日志级别
logging:
  level: debug

#数据库连接
#  datasource:
#    driver-class-name: com.
#    url: 120.0.0.1:3306
#    username: root
#    password: root
#    filters: wall,mergeStat
#    data-source-name: springboot

