spring:
  datasource:
    url: jdbc:mysql://rm-bp14f94yt54bl7l54o.mysql.rds.aliyuncs.com:3306/db_dora_syj?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    userName: dorabox_dba
    password: dora123456!@#$%^
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 5
      min-idle: 1
      initial-size: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 360000
      minEvictableIdleTimeMillis: 360000


mybatis-plus:
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#数据库连接
#  datasource:
#    driver-class-name: com.
#    url: 120.0.0.1:3306
#    username: root
#    password: root
#    filters: wall,mergeStat
#    data-source-name: springboot
