spring:
  datasource:
    url: jdbc:mysql://rm-8vb13nmd5388n09m6wo.mysql.zhangbei.rds.aliyuncs.com:3306/zhaofu?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    userName: zhaofu
    password: 2MiaoMiao
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 5
      min-idle: 1
      initial-size: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 360000
      minEvictableIdleTimeMillis: 360000
  mail:
    host: smtp.163.com
    username: 17765114126@163.com #自己的邮箱账号
    password: YXIDYBPHLBGNCNQP  #这个不是登录密码而是163授权登录的密码
    default-encoding: UTF-8
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required : true
        ssl:
          enable: true

mybatis-plus:
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

